name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: swxtz
          template: classic
          
          config_display: large
          config_timezone: America/Sao_Paulo
          config_animations: yes

          base: header, activity, repositories, metadata, community
          base_indepth: yes
          # repositories_forks: yes
          repositories: 80
          repositories_affiliations: owner, collaborator
          commits_authoring: Gustavo da Silva Mendonça, Gustavo Mendonça, swxtz, dev.gustavomendonca@protonmail.com, alf4r6@gmail.com, 82668127+swxtz@users.noreply.github.com

          plugin_lines: yes
          plugin_lines_history_limit: 3

          plugin_traffic: yes
          
          plugin_languages: yes
          plugin_languages_ignored: scss, css, html, qml, perl, lua, ruby, objective-c++, objective-c, jupyter notebook, mdx, markdown, dockerfile, javascript, dart, starlark, powershell
          plugin_languages_analysis_timeout: 200
          plugin_languages_analysis_timeout_repositories: 50
          plugin_languages_categories: programming
          plugin_languages_colors: github
          plugin_languages_details: lines
          #plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_categories: programming
          plugin_languages_recent_days: 90
          plugin_languages_recent_load: 1000
          plugin_languages_sections: most-used, recently-used
          
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: no
          
          # plugin_topics: yes
          # plugin_topics_limit: 20
          # plugin_topics_mode: icons
          # plugin_topics_sort: starred
          
          plugin_code: yes
          plugin_code_lines: 6